package cn.mofufin.morf.ui.util;

public class RxEvent {
    public static final String SUBMISSION_MPOS = "submission_mpos";
    public static final String WECHAT_REGISTER_SUCCESS = "wechat.register.success";
    public static final String CALCULATE_AMOUNT_OF_ACCOUNT="Calculate_amount_of_account";
    public static final String REFRESH_USER_MINE_INFO = "refresh_user_mine_info";
    public static final String ORDER_QUREY_REFRESH = "order_qurey_refresh";
    public static final String SCAN_QR_POSITION = "scan_qr_position";
    public static final String EDITEXT_GET_FOCUS = "editext_get_focus";
    public static final String SUBMISSION_SCAN_QR = "submission_scan_qr";
    public static final String TRANSFER_PARAMETER="transfer_parameter";
    public static final String REFRESH_BANKCARD_INFO = "refresh_bankcard_info";
    public static final String REFRESH_BANKCARD_CARDTYPE = "refresh_bankcard_cardtype";
    public static final String SUBMIT_REAL_NAME="submit_real_name";
    public static final String HOMEPAGE_CONTENT_GET="homepage_content_get";
    public static final String HOME_HORSE_LANTERN="home_horse_lantern";
    public static final String UNBIND_CARD_TRAN_PASSWORD = "unbind_card_tran_password";
    public static final String MERCHANT_BALANCE_QUREY_REFRESH = "merchant_balance_qurey_refresh";
    public static final String BALANCE_TRANSFER_FINISH = "balance_transfer_finish";
    public static final String REFRESH_QUERY_MERREBATE = "refresh_query_merrebate";
    public static final String DOLLAR_TRANSFER_FINISH = "dollar_transfer_finish";
    public static final String CASH_WITHDRAWAL_FINISH = "cash_withdrawal_finish";
    public static final String CASH_WITHDRAWAL_UPDATE_CARDINFO = "cash_withdrawal_update_cardinfo";
    public static final String RECHARGE_TO_BALANCE_FINISH = "recharge_to_balance_finish";
    public static final String RECHARGE_TO_DEPOSIT_FINISH = "recharge_to_deposit_finish";
    public static final String REFRESH_MALL_VIRTUAL_INFO = "refresh_mall_virtual_info";
    public static final String REFRESH_MALL_ACTUAL_INFO = "refresh_mall_actual_info";
    public static final String MERCHANT_DETAIL_FINISH = "merchant_detail_finish";
    public static final String MERCHANT_EXCHANGE_FINISH = "merchant_exchange_finish";
    public static final String REFRESH_MALL = "refresh_mall";
    public static final String MEMBER_COUPON_UPGRADE = "member_coupon_upgrade";
    public static final String PRODUCT_PAYMENT_FINISH = "product_payment_finish";
    public static final String REFRESH_PRODUCT_INFO = "refresh_product_info";
    public static final String REFRESH_WITHDRAW_INFO = "refresh_withdraw_info";
    public static final String REFRESH_PAYMENT_DETAILS_INFO = "refresh_payment_details_info";
    public static final String REFRESH_SELECT_CARD= "refresh_select_card";
    public static final String CHARGE_CREDIT_PAYMENT_FINISH = "charge_credit_payment_finish";
    public static final String REFRESH_RECEI_ADDRESS = "refresh_recei_address";
    public static final String REFRESH_CLEAR_RECEI_ADDRESS = "refresh_clear_recei_address";
    public static final String REFRESH_USER_ISFREEZE_STATUS = "refresh_user_isfreeze_status";
    public static final String REFRESH_LOAN_IDENTITY_STATUS = "refresh_loan_identity_status";

    public static final String ON_CALENDARS_LISTENER = "on_calendars_listener";
    public static final String ON_GENERATION_PROJECT = "on_generation_project";
    public static final String RECEIVE_GENERATION_PROJECT = "receive_generation_project";
    public static final String REPAYMENT_TITLE = "repayment_title";
    public static final String REFRESH_PROJECT = "refresh_project";
    public static final String SHOW_FRAGMENT_REPAY="show_fragment_repay";
    public static final String GENER_PROJECT_FINISH = "gener_project_finish";
    public static final String GOTO_NOTIFY_ENTRANCE = "goto_notify_entrance";
    public static final String GOTO_MINE_NOTIFY_ENTRANCE = "goto_mine_notify_entrance";
}
